name: generate and commit PlantUML diagrams
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: generate and commit diagrams
        uses: abekoh/commit-plantuml-action@v4
        with:
          bot-email: ${{ secrets.BOT_EMAIL }}
          bot-github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          enable-review-comment: true